//! Generates the "AI test-case guide" — a markdown file developers drop
//! into their repo so AI tools author import-ready test-case JSON.
//! Lives beside `import_parser` deliberately: the guide documents that
//! parser, and `tests::worked_example_round_trips` (Task 2) fails the
//! gate if the two ever drift.

use crate::model::VALID_STATUSES;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, specta::Type)]
pub enum GuideFlavor {
    Generic,
    ClaudeSkill,
    CursorRules,
    AgentsSnippet,
}

#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
pub struct GuideOptions {
    pub organization: String,
    pub project: String,
    pub area: Option<String>,
    /// Pruned Module picklist (empty + !modules_discovered => discovery failed).
    pub modules: Vec<String>,
    /// False when picklist discovery failed — the guide then carries a
    /// visible degradation note instead of silently omitting the list.
    pub modules_discovered: bool,
    pub doc_paths: Vec<String>,
    pub conventions: String,
    pub flavors: Vec<GuideFlavor>,
    /// Stamp date, passed in by the frontend (keeps this function pure).
    pub generated_on: String,
}

/// The guide's worked example. Task 2's round-trip test feeds this exact
/// string through `import_parser::parse_json`, so it can never drift from
/// what the importer accepts.
pub const WORKED_EXAMPLE_JSON: &str = r#"[
  {
    "title": "Login - valid credentials reach the dashboard",
    "steps": [
      { "action": "Open the sign-in page", "expected": "Sign-in form is shown" },
      { "action": "Enter a valid username and password and submit", "expected": "The dashboard loads and shows the signed-in user's name" }
    ],
    "tags": "smoke; login",
    "automation_status": "Not Automated",
    "module": "Login",
    "preconditions": "A test account exists"
  },
  {
    "id": 143001,
    "title": "Checkout - expired card is rejected with a clear error",
    "steps": [
      { "action": "Pay with an expired card", "expected": "An 'expired card' error is shown; no order is created" }
    ],
    "tags": "regression; checkout",
    "automation_status": "Planned",
    "module": "Checkout",
    "preconditions": ""
  }
]"#;

pub fn build_guide_body(o: &GuideOptions) -> String {
    let mut s = String::with_capacity(8 * 1024);
    let statuses = VALID_STATUSES
        .iter()
        .map(|v| format!("\"{v}\""))
        .collect::<Vec<_>>()
        .join(" or ");

    // 1. What this file is + workflow
    s.push_str(&format!(
        "# AI guide: writing test cases for Test Case Manager\n\n\
        Instructions for AI tools generating Azure DevOps test cases for \
        **{org}/{proj}**{area}. Output a JSON file in the format below; a developer \
        imports it in Test Case Manager's **Import File** tab, reviews the queue, and \
        creates the cases in Azure DevOps.\n\n\
        > Generated by Test Case Manager v{ver} on {date}. Listed values are a \
        snapshot — regenerate this guide if project picklists change.\n\n",
        org = o.organization,
        proj = o.project,
        area = o
            .area
            .as_deref()
            .map(|a| format!(" (area `{a}`)"))
            .unwrap_or_default(),
        ver = env!("CARGO_PKG_VERSION"),
        date = o.generated_on,
    ));

    // 2. Output contract
    s.push_str(
        "## Output contract\n\n\
        Produce a single `.json` file containing only a JSON array of test cases - \
        no surrounding prose, no markdown fences.\n\n",
    );

    // 3. Schema + worked example
    s.push_str(&format!(
        "## JSON format\n\n\
        Each array element is one test case:\n\n\
        | Key | Type | Notes |\n|---|---|---|\n\
        | `title` | string | Required, max 255 chars. Aliases accepted: `name`, `test_case_name`. |\n\
        | `id` | number | OPTIONAL. When present, UPDATES that exact work item; omit (or null) to CREATE. Aliases: `test_case_id`, `work_item_id`. |\n\
        | `steps` | array | Required, at least one. Each item is `{{\"action\": ..., \"expected\": ...}}` (aliases: `step` for action; `expected_result`/`result` for expected) or a plain string (action only). |\n\
        | `tags` | string | Semicolon-separated. Commas are NOT allowed in tags. |\n\
        | `automation_status` | string | Exactly {statuses}. Anything else is replaced with \"Not Automated\" and flagged. |\n\
        | `module` | string | Alias: `module_value`. Only use the allowed values listed below. |\n\
        | `preconditions` | string | Setup/state, not steps. Alias: `prerequisites`. |\n\n\
        ### Worked example (one create, one update)\n\n```json\n{example}\n```\n\n",
        example = WORKED_EXAMPLE_JSON,
    ));

    // 4. Hard rules
    s.push_str(&format!(
        "## Hard rules\n\n\
        - `automation_status` MUST be exactly {statuses}.\n\
        - Every case MUST have a non-empty `title` (<= 255 chars) and at least one step with a non-empty action.\n\
        - Tags MUST be semicolon-separated - never commas.\n\
        - An `id` updates that exact work item. Matching by title NEVER updates - omit `id` to create.\n\
        - `module` MUST come from the allowed values below - do not invent new ones.\n\n",
    ));

    // 5. Allowed values (custom layer, with visible degradation)
    s.push_str("## Allowed values\n\n");
    if o.modules_discovered && !o.modules.is_empty() {
        s.push_str("**Module** (use exactly one of):\n");
        for m in &o.modules {
            s.push_str(&format!("- `{m}`\n"));
        }
        s.push('\n');
    } else if o.modules_discovered {
        s.push_str(
            "No Module values are defined for this project. Leave `module` empty unless \
            the developer tells you otherwise.\n\n",
        );
    } else {
        s.push_str(
            "Module values could not be discovered from Azure DevOps when this guide \
            was generated. Ask the developer for the allowed Module values before using any.\n\n",
        );
    }

    // 6. Repo documentation (omitted when none given)
    if !o.doc_paths.is_empty() {
        s.push_str("## Repository documentation\n\nBefore writing cases, read:\n");
        for p in &o.doc_paths {
            s.push_str(&format!("- `{p}`\n"));
        }
        s.push('\n');
    }

    // 7. Team conventions (omitted when empty)
    if !o.conventions.trim().is_empty() {
        s.push_str(&format!("## Team conventions\n\n{}\n\n", o.conventions.trim()));
    }

    // 8. Craft guidance
    s.push_str(
        "## Writing good test cases\n\n\
        - One observable behavior per case; split compound scenarios.\n\
        - Actions are imperative and atomic (\"Click Save\"), expecteds are observable outcomes.\n\
        - Cover the negative and edge paths, not just the happy path.\n\
        - Preconditions describe required state, not actions to perform.\n",
    );
    s
}

/// Thin packaging around the single-source body — flavors never fork the
/// content, only wrap it. Returned paths are relative to the chosen repo root.
pub fn flavor_files(body: &str, flavors: &[GuideFlavor]) -> Vec<(String, String)> {
    flavors
        .iter()
        .map(|f| match f {
            GuideFlavor::Generic => ("AI_TEST_CASES.md".to_string(), body.to_string()),
            GuideFlavor::ClaudeSkill => (
                ".claude/skills/generate-test-cases/SKILL.md".to_string(),
                format!(
                    "---\nname: generate-test-cases\ndescription: Write Azure DevOps \
                    test cases as JSON importable by Test Case Manager. Use when asked \
                    to create, write, or generate test cases for this project.\n---\n\n{body}"
                ),
            ),
            GuideFlavor::CursorRules => (
                ".cursor/rules/test-cases.mdc".to_string(),
                format!(
                    "---\ndescription: Writing test cases importable by Test Case Manager\nalwaysApply: false\n---\n\n{body}"
                ),
            ),
            GuideFlavor::AgentsSnippet => (
                "AGENTS-test-cases.md".to_string(),
                format!(
                    "<!-- Snippet: append this section to your existing AGENTS.md -->\n\n\
                    ## Writing test cases for Test Case Manager\n\n{body}"
                ),
            ),
        })
        .collect()
}
