//! Generates the "AI test-case guide" — a markdown file developers drop
//! into their repo so AI tools author import-ready test-case JSON.
//! Lives beside `import_parser` deliberately: the guide documents that
//! parser, and `tests::worked_example_round_trips` (Task 2) fails the
//! gate if the two ever drift.

use crate::model::VALID_STATUSES;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, specta::Type)]
pub enum GuideFlavor {
    Generic,
    ClaudeSkill,
    CursorRules,
    AgentsSnippet,
}

#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
pub struct GuideOptions {
    pub organization: String,
    pub project: String,
    pub area: Option<String>,
    /// Pruned Module picklist (empty + !modules_discovered => discovery failed).
    pub modules: Vec<String>,
    pub tags: Vec<String>,
    /// False when picklist discovery failed — the guide then carries a
    /// visible degradation note instead of silently omitting the list.
    pub modules_discovered: bool,
    pub doc_paths: Vec<String>,
    pub conventions: String,
    pub flavors: Vec<GuideFlavor>,
    /// Stamp date, passed in by the frontend (keeps this function pure).
    pub generated_on: String,
}

/// The guide's worked example. Task 2's round-trip test feeds this exact
/// string through `import_parser::parse_json`, so it can never drift from
/// what the importer accepts.
pub const WORKED_EXAMPLE_JSON: &str = r#"[
  {
    "title": "Login - valid credentials reach the dashboard",
    "steps": [
      { "action": "Open the sign-in page", "expected": "Sign-in form is shown" },
      { "action": "Enter a valid username and password and submit", "expected": "The dashboard loads and shows the signed-in user's name" }
    ],
    "tags": "smoke; login",
    "automation_status": "Not Automated",
    "module": "Login",
    "preconditions": "A test account exists"
  },
  {
    "id": 143001,
    "title": "Checkout - expired card is rejected with a clear error",
    "steps": [
      { "action": "Pay with an expired card", "expected": "An 'expired card' error is shown; no order is created" }
    ],
    "tags": "regression; checkout",
    "automation_status": "Planned",
    "module": "Checkout",
    "preconditions": ""
  }
]"#;

pub fn build_guide_body(o: &GuideOptions) -> String {
    let mut s = String::with_capacity(8 * 1024);
    let statuses = VALID_STATUSES
        .iter()
        .map(|v| format!("\"{v}\""))
        .collect::<Vec<_>>()
        .join(" or ");

    // 1. What this file is + workflow
    s.push_str(&format!(
        "# AI guide: writing test cases for Test Case Manager\n\n\
        Instructions for AI tools generating Azure DevOps test cases for \
        **{org}/{proj}**{area}. Output a JSON file in the format below; a developer \
        imports it in Test Case Manager's **Import File** tab, reviews the queue, and \
        creates the cases in Azure DevOps.\n\n\
        > Generated by Test Case Manager v{ver} on {date}. Listed values are a \
        snapshot — regenerate this guide if project picklists change.\n\n",
        org = o.organization,
        proj = o.project,
        area = o
            .area
            .as_deref()
            .map(|a| format!(" (area `{a}`)"))
            .unwrap_or_default(),
        ver = env!("CARGO_PKG_VERSION"),
        date = o.generated_on,
    ));

    // 2. Output contract
    s.push_str(
        "## Output contract\n\n\
        Produce a single `.json` file containing only a JSON array of test cases - \
        no surrounding prose, no markdown fences.\n\n",
    );

    // 3. Schema + worked example
    s.push_str(&format!(
        "## JSON format\n\n\
        Each array element is one test case:\n\n\
        | Key | Type | Notes |\n|---|---|---|\n\
        | `title` | string | Required, max 255 chars. Aliases accepted: `name`, `test_case_name`. |\n\
        | `id` | number | OPTIONAL. When present, UPDATES that exact work item; omit (or null) to CREATE. Aliases: `test_case_id`, `work_item_id`. |\n\
        | `steps` | array | Required, at least one. Each item is `{{\"action\": ..., \"expected\": ...}}` (aliases: `step` for action; `expected_result`/`result` for expected) or a plain string (action only). |\n\
        | `tags` | string | Semicolon-separated. Commas are NOT allowed in tags. |\n\
        | `automation_status` | string | Exactly {statuses}. Anything else is replaced with \"Not Automated\" and flagged. |\n\
        | `module` | string | Alias: `module_value`. Only use the allowed values listed below. |\n\
        | `preconditions` | string | Setup/state, not steps. Alias: `prerequisites`. |\n\n\
        ### Worked example (one create, one update)\n\n```json\n{example}\n```\n\n",
        example = WORKED_EXAMPLE_JSON,
    ));

    // 4. Hard rules
    s.push_str(&format!(
        "## Hard rules\n\n\
        - `automation_status` MUST be exactly {statuses}.\n\
        - Every case MUST have a non-empty `title` (<= 255 chars) and at least one step with a non-empty action.\n\
        - Tags MUST be semicolon-separated - never commas.\n\
        - An `id` updates that exact work item. Matching by title NEVER updates - omit `id` to create.\n\
        - `module` MUST come from the allowed values below - do not invent new ones.\n\n",
    ));

    // 5. Allowed values (custom layer, with visible degradation)
    s.push_str("## Allowed values\n\n");
    if o.modules_discovered && !o.modules.is_empty() {
        s.push_str("**Module** (use exactly one of):\n");
        for m in &o.modules {
            s.push_str(&format!("- `{m}`\n"));
        }
        s.push('\n');
    } else {
        s.push_str(
            "Module values could not be discovered from Azure DevOps when this guide \
            was generated. Ask the developer for the allowed Module values before using any.\n\n",
        );
    }
    if !o.tags.is_empty() {
        s.push_str("**Tags in use** (prefer these; new tags are allowed):\n");
        for t in &o.tags {
            s.push_str(&format!("- `{t}`\n"));
        }
        s.push('\n');
    }

    // 6. Repo documentation (omitted when none given)
    if !o.doc_paths.is_empty() {
        s.push_str("## Repository documentation\n\nBefore writing cases, read:\n");
        for p in &o.doc_paths {
            s.push_str(&format!("- `{p}`\n"));
        }
        s.push('\n');
    }

    // 7. Team conventions (omitted when empty)
    if !o.conventions.trim().is_empty() {
        s.push_str(&format!("## Team conventions\n\n{}\n\n", o.conventions.trim()));
    }

    // 8. Craft guidance
    s.push_str(
        "## Writing good test cases\n\n\
        - One observable behavior per case; split compound scenarios.\n\
        - Actions are imperative and atomic (\"Click Save\"), expecteds are observable outcomes.\n\
        - Cover the negative and edge paths, not just the happy path.\n\
        - Preconditions describe required state, not actions to perform.\n",
    );
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn opts() -> GuideOptions {
        GuideOptions {
            organization: "acme".into(),
            project: "Web".into(),
            area: Some("Web\\Gamma Guardians".into()),
            modules: vec!["Login".into(), "Checkout".into()],
            tags: vec!["smoke".into(), "regression".into()],
            modules_discovered: true,
            doc_paths: vec!["docs/screens/**".into(), "README.md".into()],
            conventions: "Tag UI cases with 'ui'.".into(),
            flavors: vec![GuideFlavor::Generic],
            generated_on: "2026-07-20".into(),
        }
    }

    #[test]
    fn body_contains_fixed_sections_and_custom_values() {
        let body = build_guide_body(&opts());
        // Fixed layer
        assert!(body.contains("Test Case Manager"));
        assert!(body.contains("Import File"));           // workflow section
        assert!(body.contains("```json"));               // worked example fence
        assert!(body.contains("\"Not Automated\""));     // statuses from VALID_STATUSES
        assert!(body.contains("\"Planned\""));
        assert!(body.contains("semicolon"));             // tag separator rule
        // Custom layer
        assert!(body.contains("Login") && body.contains("Checkout"));
        assert!(body.contains("smoke"));
        assert!(body.contains("docs/screens/**"));
        assert!(body.contains("Tag UI cases with 'ui'."));
        assert!(body.contains("2026-07-20"));            // snapshot stamp
        assert!(body.contains(env!("CARGO_PKG_VERSION")));
    }

    #[test]
    fn empty_custom_inputs_omit_their_sections() {
        let mut o = opts();
        o.doc_paths.clear();
        o.conventions = String::new();
        o.modules.clear();
        o.modules_discovered = false;
        o.tags.clear();
        let body = build_guide_body(&o);
        assert!(!body.contains("## Repository documentation"));
        assert!(!body.contains("## Team conventions"));
        // Discovery failure => visible degradation note instead of a list
        assert!(body.contains("could not be discovered"));
    }

    #[test]
    fn body_is_deterministic() {
        assert_eq!(build_guide_body(&opts()), build_guide_body(&opts()));
    }

    /// THE drift gate: the guide's own worked example must parse through
    /// the real importer. If the import format changes without updating
    /// the guide (or vice versa), this fails the build.
    #[test]
    fn worked_example_round_trips_through_the_importer() {
        let dir = std::env::temp_dir().join("tcm_ai_guide_test");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join(format!("example-{}.json", std::process::id()));
        std::fs::write(&path, WORKED_EXAMPLE_JSON).unwrap();

        let (cases, warnings) =
            crate::import_parser::parse_file(path.to_str().unwrap()).unwrap();

        assert_eq!(warnings, Vec::<String>::new(), "example must import warning-free");
        assert_eq!(cases.len(), 2, "guide's worked example must contain exactly 2 cases");

        // Create vs update semantics
        assert_eq!(cases[0].update_id, None, "case 0 has no `id` in the guide's example - it must round-trip as a CREATE");
        assert_eq!(
            cases[1].update_id,
            Some(143001),
            "case 1's `id` must round-trip as an UPDATE of that exact work item"
        );

        // Case 0 ("Login") - every field the guide's worked example advertises
        // must survive the trip through the real importer.
        assert_eq!(cases[0].steps.len(), 2, "case 0 must keep both of its steps");
        assert_eq!(
            cases[0].steps[0].action, "Open the sign-in page",
            "case 0 step 1 action drifted from the guide's worked example"
        );
        assert_eq!(
            cases[0].steps[0].expected, "Sign-in form is shown",
            "case 0 step 1 expected drifted from the guide's worked example"
        );
        assert_eq!(
            cases[0].steps[1].action,
            "Enter a valid username and password and submit",
            "case 0 step 2 action drifted from the guide's worked example"
        );
        assert_eq!(
            cases[0].steps[1].expected,
            "The dashboard loads and shows the signed-in user's name",
            "case 0 step 2 expected drifted from the guide's worked example"
        );
        assert_eq!(
            cases[0].tags, "smoke; login",
            "case 0 tags must round-trip as the semicolon-separated string the guide shows"
        );
        assert_eq!(
            cases[0].automation_status, "Not Automated",
            "case 0 automation_status drifted from the guide's worked example"
        );
        assert_eq!(
            cases[0].module_value, "Login",
            "case 0 module_value drifted from the guide's worked example"
        );
        assert_eq!(
            cases[0].preconditions, "A test account exists",
            "case 0 preconditions drifted from the guide's worked example - preconditions has no warning path in the importer, so this assertion is the only thing that would catch silent drift"
        );

        // Case 1 ("Checkout") - same coverage, including the update path.
        assert_eq!(cases[1].steps.len(), 1, "case 1 must keep its single step");
        assert_eq!(
            cases[1].steps[0].action, "Pay with an expired card",
            "case 1 step 1 action drifted from the guide's worked example"
        );
        assert_eq!(
            cases[1].steps[0].expected,
            "An 'expired card' error is shown; no order is created",
            "case 1 step 1 expected drifted from the guide's worked example"
        );
        assert_eq!(
            cases[1].tags, "regression; checkout",
            "case 1 tags must round-trip as the semicolon-separated string the guide shows"
        );
        assert_eq!(
            cases[1].automation_status, "Planned",
            "case 1 automation_status drifted from the guide's worked example"
        );
        assert_eq!(
            cases[1].module_value, "Checkout",
            "case 1 module_value drifted from the guide's worked example"
        );
        assert_eq!(
            cases[1].preconditions, "",
            "case 1 preconditions must round-trip as empty, matching the guide's worked example"
        );

        // Both must be submit-ready
        assert!(
            cases[0].is_valid().is_ok() && cases[1].is_valid().is_ok(),
            "both cases from the guide's worked example must pass TestCase::is_valid()"
        );

        let _ = std::fs::remove_file(&path);
        let _ = std::fs::remove_dir(&dir);
    }
}
