// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	ping: (msg: string) => __TAURI_INVOKE<string>("ping", { msg }),
	authStatus: () => __TAURI_INVOKE<AuthStatus>("auth_status"),
	signIn: () => typedError<AuthStatus, string>(__TAURI_INVOKE("sign_in")),
	listProjects: (organization: string) => typedError<Project[], AdoError>(__TAURI_INVOKE("list_projects", { organization })),
	listOrgs: () => typedError<Org[], AdoError>(__TAURI_INVOKE("list_orgs")),
	searchPbis: (organization: string, project: string, query: string) => typedError<PbiHit[], AdoError>(__TAURI_INVOKE("search_pbis", { organization, project, query })),
	pbiTestCases: (organization: string, pbiId: number) => typedError<TestCaseSummary[], AdoError>(__TAURI_INVOKE("pbi_test_cases", { organization, pbiId })),
	parseImportFile: (path: string) => typedError<ImportResult, string>(__TAURI_INVOKE("parse_import_file", { path })),
	exportQueue: (path: string, queue: TestCase[]) => typedError<null, string>(__TAURI_INVOKE("export_queue", { path, queue })),
	writeTemplate: (path: string) => typedError<null, string>(__TAURI_INVOKE("write_template", { path })),
	/**
	 *  Serial creation loop ported from v1 CreationWorker: one item at a time,
	 *  500 ms spacing (rate-limit respect), new cases linked to the PBI, updates
	 *  patched in place. A failed item never aborts the rest.
	 */
	submitQueue: (organization: string, project: string, pbiId: number, queue: TestCase[], moduleRef: string | null, preconditionsRef: string | null) => typedError<SubmitItemResult[], string>(__TAURI_INVOKE("submit_queue", { organization, project, pbiId, queue, moduleRef, preconditionsRef })),
	/**  Find-or-create the PBI's requirement suite and return it with its plan. */
	ensurePbiSuite: (organization: string, project: string, pbiId: number) => typedError<EnsuredSuite, AdoError>(__TAURI_INVOKE("ensure_pbi_suite", { organization, project, pbiId })),
	listTestPoints: (organization: string, project: string, planId: number, suiteId: number) => typedError<TestPoint[], AdoError>(__TAURI_INVOKE("list_test_points", { organization, project, planId, suiteId })),
	/**
	 *  Full manual-run lifecycle ported from v1 run_screen submission: create a
	 *  run seeded from the points, map each point to its auto-created result,
	 *  PATCH outcomes, complete the run. Returns the run's web URL.
	 */
	submitTestRun: (organization: string, project: string, planId: number, runName: string, outcomes: PointOutcome[]) => typedError<RunCreated, AdoError>(__TAURI_INVOKE("submit_test_run", { organization, project, planId, runName, outcomes })),
	fetchBoard: (organization: string, project: string) => typedError<BoardData, AdoError>(__TAURI_INVOKE("fetch_board", { organization, project })),
	/**
	 *  Move a board item into a column: resolves the target state exactly like
	 *  v1 (_state_for_column) and PATCHes System.State. Returns the state set.
	 */
	moveBoardItem: (organization: string, project: string, itemId: number, workItemType: string, column: string) => typedError<string, AdoError>(__TAURI_INVOKE("move_board_item", { organization, project, itemId, workItemType, column })),
	/**  Non-blocking update check; Some(version) when a newer build is published. */
	checkUpdate: () => __TAURI_INVOKE<string | null>("check_update"),
	/**  Download the pending update and restart into it. */
	applyUpdate: () => typedError<null, string>(__TAURI_INVOKE("apply_update")),
	listTestCaseFields: (organization: string, project: string) => typedError<FieldRef[], AdoError>(__TAURI_INVOKE("list_test_case_fields", { organization, project })),
	pbiTestCasesFull: (organization: string, pbiId: number, moduleRef: string | null, preconditionsRef: string | null) => typedError<TestCaseFull[], AdoError>(__TAURI_INVOKE("pbi_test_cases_full", { organization, pbiId, moduleRef, preconditionsRef })),
	/**
	 *  Save one existing case from the editor (no suite-ensure, no pacing).
	 *  The case must carry update_id; blank-skip semantics apply as always.
	 */
	updateTestCase: (organization: string, project: string, tc: TestCase, moduleRef: string | null, preconditionsRef: string | null) => typedError<null, string>(__TAURI_INVOKE("update_test_case", { organization, project, tc, moduleRef, preconditionsRef })),
	exportQueueJson: (path: string, queue: TestCase[]) => typedError<null, string>(__TAURI_INVOKE("export_queue_json", { path, queue })),
	listPlansWithSuites: (organization: string, project: string) => typedError<PlanWithSuites[], AdoError>(__TAURI_INVOKE("list_plans_with_suites", { organization, project })),
};

/** Events */
export const events = {
	submitProgress: makeEvent<SubmitProgress>("submit-progress"),
};

/* Types */
export type AdoError = { kind: "Unauthorized" } | { kind: "RateLimited"; detail: {
	retry_after_secs: number,
} } | { kind: "Forbidden" } | { kind: "NotFound" } | { kind: "Http"; detail: {
	status: number,
	body: string,
} } | { kind: "Network"; detail: string };

export type AuthStatus = {
	signed_in: boolean,
	account: string | null,
};

export type BoardData = {
	items: BoardItem[],
	states_by_type: { [key in string]: StateInfo[] },
};

export type BoardItem = {
	id: number,
	title: string,
	work_item_type: string,
	state: string,
	state_color: string,
	/**  "To Do" | "In Progress" | "Done"; None = hidden (Removed). */
	column: string | null,
	assigned_to: string,
	tags: string,
	priority: number | null,
	changed_date: string,
};

export type EnsuredSuite = {
	plan_id: number,
	plan_name: string,
	suite_id: number,
};

export type FieldRef = {
	name: string,
	reference_name: string,
};

export type ImportResult = {
	cases: TestCase[],
	warnings: string[],
};

export type Org = {
	name: string,
	url: string,
};

export type PbiHit = {
	id: number,
	title: string,
	work_item_type: string,
};

export type PlanWithSuites = {
	plan: TestPlan,
	suites: SuiteRef[],
};

export type PointOutcome = {
	point_id: number,
	/**  Passed / Failed / Blocked / NotApplicable. */
	outcome: string,
	comment: string | null,
	duration_ms: number | null,
};

export type Project = {
	id: string,
	name: string,
};

export type RunCreated = {
	run_id: number,
	web_url: string,
};

export type StateInfo = {
	name: string,
	color: string,
	category: string,
};

export type Step = {
	action: string,
	expected: string,
};

export type SubmitItemResult = {
	index: number,
	title: string,
	/**  "created" | "updated" | "failed" */
	action: string,
	id: number | null,
	error: string | null,
};

/**  Emitted once per queue item while submit_queue runs. */
export type SubmitProgress = {
	index: number,
	total: number,
	title: string,
	/**  "created" | "updated" | "failed" */
	action: string,
};

export type SuiteRef = {
	id: number,
	name: string,
	suite_type: string,
	requirement_id: number | null,
};

export type TestCase = {
	title: string,
	steps: Step[],
	/**  Semicolon-separated. */
	tags: string,
	/**  "Not Automated" or "Planned". */
	automation_status: string,
	module_value: string,
	preconditions: string,
	/**  When set, update this existing work item instead of creating a new one. */
	update_id: number | null,
};

/**
 *  A fully-loaded Test Case for the editor: steps parsed from the XML blob,
 *  preconditions flattened to plain text. `id` doubles as update_id when the
 *  editor saves.
 */
export type TestCaseFull = {
	id: number,
	title: string,
	tags: string,
	automation_status: string,
	steps: Step[],
	module_value: string,
	preconditions: string,
};

export type TestCaseSummary = {
	id: number,
	title: string,
	tags: string,
	automation_status: string,
};

export type TestPlan = {
	id: number,
	name: string,
	area_path: string,
	root_suite_id: number | null,
};

export type TestPoint = {
	point_id: number,
	test_case_id: number | null,
	test_case_name: string,
	config_name: string,
	tester: string,
	last_outcome: string,
	last_run_id: number | null,
	last_result_id: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

