// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	ping: (msg: string) => __TAURI_INVOKE<string>("ping", { msg }),
	authStatus: () => __TAURI_INVOKE<AuthStatus>("auth_status"),
	signIn: () => typedError<AuthStatus, string>(__TAURI_INVOKE("sign_in")),
	listProjects: (organization: string) => typedError<Project[], AdoError>(__TAURI_INVOKE("list_projects", { organization })),
	listOrgs: () => typedError<Org[], AdoError>(__TAURI_INVOKE("list_orgs")),
	searchPbis: (organization: string, project: string, query: string) => typedError<PbiHit[], AdoError>(__TAURI_INVOKE("search_pbis", { organization, project, query })),
	pbiTestCases: (organization: string, pbiId: number) => typedError<TestCaseSummary[], AdoError>(__TAURI_INVOKE("pbi_test_cases", { organization, pbiId })),
	parseImportFile: (path: string) => typedError<ImportResult, string>(__TAURI_INVOKE("parse_import_file", { path })),
	exportQueue: (path: string, queue: TestCase[]) => typedError<null, string>(__TAURI_INVOKE("export_queue", { path, queue })),
	writeTemplate: (path: string) => typedError<null, string>(__TAURI_INVOKE("write_template", { path })),
	/**
	 *  Serial creation loop ported from v1 CreationWorker: one item at a time,
	 *  500 ms spacing (rate-limit respect), new cases linked to the PBI, updates
	 *  patched in place. A failed item never aborts the rest.
	 */
	submitQueue: (organization: string, project: string, pbiId: number, queue: TestCase[], moduleRef: string | null, preconditionsRef: string | null, areaPath: string | null, iterationPath: string | null) => typedError<SubmitItemResult[], string>(__TAURI_INVOKE("submit_queue", { organization, project, pbiId, queue, moduleRef, preconditionsRef, areaPath, iterationPath })),
	/**  Find-or-create the PBI's requirement suite and return it with its plan. */
	ensurePbiSuite: (organization: string, project: string, pbiId: number) => typedError<EnsuredSuite, AdoError>(__TAURI_INVOKE("ensure_pbi_suite", { organization, project, pbiId })),
	listTestPoints: (organization: string, project: string, planId: number, suiteId: number) => typedError<TestPoint[], AdoError>(__TAURI_INVOKE("list_test_points", { organization, project, planId, suiteId })),
	/**
	 *  Full manual-run lifecycle ported from v1 run_screen submission: create a
	 *  run seeded from the points, map each point to its auto-created result,
	 *  PATCH outcomes, complete the run. Returns the run's web URL.
	 */
	submitTestRun: (organization: string, project: string, planId: number, runName: string, outcomes: PointOutcome[]) => typedError<RunCreated, AdoError>(__TAURI_INVOKE("submit_test_run", { organization, project, planId, runName, outcomes })),
	fetchBoard: (organization: string, project: string, team: string | null) => typedError<BoardData, AdoError>(__TAURI_INVOKE("fetch_board", { organization, project, team })),
	/**  v1 (_state_for_column) and PATCHes System.State. Returns the state set. */
	moveBoardItem: (organization: string, project: string, itemId: number, workItemType: string, column: string) => typedError<string, AdoError>(__TAURI_INVOKE("move_board_item", { organization, project, itemId, workItemType, column })),
	/**
	 *  Move a board item into a column: resolves the target state exactly like
	 *  Start streaming AudioSpectrum events from system-audio loopback (the
	 *  flask equalizer rings). No-op if already running; failures are silent by
	 *  design - the feature is decorative.
	 */
	audioCaptureStart: () => typedError<null, string>(__TAURI_INVOKE("audio_capture_start")),
	/**  Stop the AudioSpectrum stream (last UI subscriber unmounted). */
	audioCaptureStop: () => __TAURI_INVOKE<void>("audio_capture_stop"),
	/**  Non-blocking update check; Some(version) when a newer build is published. */
	checkUpdate: () => __TAURI_INVOKE<string | null>("check_update"),
	/**  Download the pending update and restart into it. */
	applyUpdate: () => typedError<null, string>(__TAURI_INVOKE("apply_update")),
	listTestCaseFields: (organization: string, project: string) => typedError<FieldRef[], AdoError>(__TAURI_INVOKE("list_test_case_fields", { organization, project })),
	pbiTestCasesFull: (organization: string, pbiId: number, moduleRef: string | null, preconditionsRef: string | null) => typedError<TestCaseFull[], AdoError>(__TAURI_INVOKE("pbi_test_cases_full", { organization, pbiId, moduleRef, preconditionsRef })),
	/**
	 *  Save one existing case from the editor (no suite-ensure, no pacing).
	 *  The case must carry update_id; blank-skip semantics apply as always.
	 */
	updateTestCase: (organization: string, project: string, tc: TestCase, moduleRef: string | null, preconditionsRef: string | null) => typedError<null, string>(__TAURI_INVOKE("update_test_case", { organization, project, tc, moduleRef, preconditionsRef })),
	exportQueueJson: (path: string, queue: TestCase[]) => typedError<null, string>(__TAURI_INVOKE("export_queue_json", { path, queue })),
	listPlansWithSuites: (organization: string, project: string) => typedError<PlanWithSuites[], AdoError>(__TAURI_INVOKE("list_plans_with_suites", { organization, project })),
	getResultDetail: (organization: string, project: string, runId: number, resultId: number) => typedError<ResultDetail, AdoError>(__TAURI_INVOKE("get_result_detail", { organization, project, runId, resultId })),
	captureScreens: () => typedError<ScreenShot[], string>(__TAURI_INVOKE("capture_screens")),
	/**
	 *  File a Bug (or Issue on Basic-process projects) for a failed case:
	 *  Related links to the test case + PBI, screenshots attached. POST only.
	 */
	fileBug: (organization: string, project: string, title: string, reproText: string, testCaseId: number, pbiId: number, screenshotsB64: string[]) => typedError<FiledBug, string>(__TAURI_INVOKE("file_bug", { organization, project, title, reproText, testCaseId, pbiId, screenshotsB64 })),
	listTeams: (organization: string, project: string) => typedError<TeamRef[], AdoError>(__TAURI_INVOKE("list_teams", { organization, project })),
	listTeamMembers: (organization: string, project: string) => typedError<Member[], AdoError>(__TAURI_INVOKE("list_team_members", { organization, project })),
	workItemDetail: (organization: string, project: string, id: number) => typedError<WorkItemDetail, AdoError>(__TAURI_INVOKE("work_item_detail", { organization, project, id })),
	/**
	 *  PATCH a work item's fields (create-or-replace 'add' ops, only the
	 *  changed refs). ADO 4xx (invalid transition / required field) surfaces
	 *  verbatim for the drawer to show.
	 */
	updateWorkItem: (organization: string, project: string, id: number, patches: FieldPatch[]) => typedError<null, AdoError>(__TAURI_INVOKE("update_work_item", { organization, project, id, patches })),
	activityValues: (organization: string, project: string, wiType: string) => typedError<string[], AdoError>(__TAURI_INVOKE("activity_values", { organization, project, wiType })),
	workItemComments: (organization: string, project: string, id: number) => typedError<WorkComment[], AdoError>(__TAURI_INVOKE("work_item_comments", { organization, project, id })),
	addComment: (organization: string, project: string, id: number, text: string) => typedError<null, AdoError>(__TAURI_INVOKE("add_comment", { organization, project, id, text })),
	/**  Best-effort avatar fetch (None -> initials disc in the UI). */
	avatarB64: (url: string) => __TAURI_INVOKE<string | null>("avatar_b64", { url }),
	/**  Quick create a Task/Bug from the board, optionally assigned to me. */
	quickCreateItem: (organization: string, project: string, wiType: string, title: string, assignToMe: boolean) => typedError<number, AdoError>(__TAURI_INVOKE("quick_create_item", { organization, project, wiType, title, assignToMe })),
	/**  The project's Area or Iteration paths for the create pickers. */
	classificationPaths: (organization: string, project: string, structure: string) => typedError<string[], AdoError>(__TAURI_INVOKE("classification_paths", { organization, project, structure })),
	/**  Stop the running submit loop after the in-flight item finishes. */
	cancelSubmit: () => __TAURI_INVOKE<void>("cancel_submit"),
	exportQueueHtml: (path: string, queue: TestCase[], subtitle: string) => typedError<null, string>(__TAURI_INVOKE("export_queue_html", { path, queue, subtitle })),
	listProjectTags: (organization: string, project: string) => typedError<string[], AdoError>(__TAURI_INVOKE("list_project_tags", { organization, project })),
	resultScreenshots: (organization: string, project: string, runId: number, resultId: number) => typedError<string[], AdoError>(__TAURI_INVOKE("result_screenshots", { organization, project, runId, resultId })),
	/**
	 *  Render the queue's HTML report to a temp file and open it in the
	 *  default browser - v1's "View" behaviour, no save dialog.
	 */
	viewQueueHtml: (queue: TestCase[], subtitle: string) => typedError<null, string>(__TAURI_INVOKE("view_queue_html", { queue, subtitle })),
	/**  Test cases for arbitrary ids (suite browser handoffs). */
	testCasesByIds: (organization: string, ids: number[], moduleRef: string | null, preconditionsRef: string | null) => typedError<TestCaseFull[], AdoError>(__TAURI_INVOKE("test_cases_by_ids", { organization, ids, moduleRef, preconditionsRef })),
	/**
	 *  Values for ANY Test Case field: the definition's picklist when one
	 *  exists, otherwise the distinct values in use on the project's Test
	 *  Cases (many orgs keep Modules as plain values, not allowedValues).
	 */
	testCaseFieldValues: (organization: string, project: string, fieldRef: string) => typedError<string[], AdoError>(__TAURI_INVOKE("test_case_field_values", { organization, project, fieldRef })),
	/**
	 *  Read-only suite lookup for background prefetch: finds the PBI's
	 *  requirement suite if one exists anywhere, but NEVER creates a plan or
	 *  suite (creation stays on the Run Tests screen where the user asked).
	 */
	findPbiSuite: (organization: string, project: string, pbiId: number) => typedError<{
	plan_id: number,
	plan_name: string,
	suite_id: number,
} | null, AdoError>(__TAURI_INVOKE("find_pbi_suite", { organization, project, pbiId })),
	/**  Recent outcome history per test case for a plan (last 5, newest first). */
	runHistory: (organization: string, project: string, planId: number) => typedError<CaseHistory[], AdoError>(__TAURI_INVOKE("run_history", { organization, project, planId })),
	/**
	 *  Execution report for one or more suites (a folder passes all its
	 *  descendants): gathers points + failure details (comments, linked bugs),
	 *  renders the failures-first HTML to a temp file and opens the browser.
	 *  GET-only against ADO; writes only the local temp file.
	 */
	viewExecutionReport: (organization: string, project: string, planId: number, suiteIds: number[], title: string) => typedError<null, string>(__TAURI_INVOKE("view_execution_report", { organization, project, planId, suiteIds, title })),
	/**  Read any file for attaching to a result (name + base64 bytes). */
	readFileB64: (path: string) => typedError<RunAttachmentOut, string>(__TAURI_INVOKE("read_file_b64", { path })),
	/**
	 *  Launch the Windows snipping overlay (result lands on the clipboard; the
	 *  runner polls and attaches it).
	 */
	openSnip: () => typedError<null, string>(__TAURI_INVOKE("open_snip")),
};

/** Events */
export const events = {
	audioSpectrum: makeEvent<AudioSpectrum>("audio-spectrum"),
	submitProgress: makeEvent<SubmitProgress>("submit-progress"),
	suiteScanProgress: makeEvent<SuiteScanProgress>("suite-scan-progress"),
};

/* Types */
export type AdoError = { kind: "Unauthorized" } | { kind: "RateLimited"; detail: {
	retry_after_secs: number,
} } | { kind: "Forbidden" } | { kind: "NotFound" } | { kind: "Http"; detail: {
	status: number,
	body: string,
} } | { kind: "Network"; detail: string };

export type AudioSpectrum = {
	/**  `BAND_COUNT` values in 0..=1, low frequencies first. */
	bands: (number | null)[],
};

export type AuthStatus = {
	signed_in: boolean,
	account: string | null,
};

export type BoardData = {
	items: BoardItem[],
	states_by_type: { [key in string]: StateInfo[] },
};

export type BoardItem = {
	id: number,
	title: string,
	work_item_type: string,
	state: string,
	state_color: string,
	/**  "To Do" | "In Progress" | "Done"; None = hidden (Removed). */
	column: string | null,
	assigned_to: string,
	tags: string,
	priority: number | null,
	changed_date: string,
};

/**  One test case's recent outcomes (newest first, capped at 5). */
export type CaseHistory = {
	test_case_id: number,
	outcomes: RunOutcome[],
};

export type EnsuredSuite = {
	plan_id: number,
	plan_name: string,
	suite_id: number,
};

/**  A single field on an extra page. */
export type ExtraField = {
	label: string,
	reference_name: string,
	/**  "html" (rich text), "pick" (allowed values), or "text". */
	kind: string,
	/**  Allowed values when kind == "pick". */
	allowed: string[],
	/**  Current raw value (HTML for html fields). */
	value: string,
};

/**  One custom form page (an ADO tab) and its editable fields, in form order. */
export type ExtraPage = {
	name: string,
	fields: ExtraField[],
};

export type FieldPatch = {
	reference_name: string,
	value: string,
};

export type FieldRef = {
	name: string,
	reference_name: string,
};

export type FiledBug = {
	id: number,
	url: string,
};

export type ImportResult = {
	cases: TestCase[],
	warnings: string[],
};

export type Member = {
	display_name: string,
	unique_name: string,
};

export type Org = {
	name: string,
	url: string,
};

export type PbiHit = {
	id: number,
	title: string,
	work_item_type: string,
};

export type PlanWithSuites = {
	plan: TestPlan,
	suites: SuiteRef[],
};

export type PointOutcome = {
	point_id: number,
	/**  Passed / Failed / Blocked / NotApplicable. */
	outcome: string,
	comment: string | null,
	duration_ms: number | null,
	/**
	 *  The case's real step ids (from TestCaseFull.step_ids), aligned with
	 *  step_outcomes; both present only when steps were marked individually.
	 */
	step_ids: string[] | null,
	step_outcomes: (string | null)[] | null,
	/**  Files (screenshots or anything else) to attach to this result. */
	attachments: RunAttachment[] | null,
	/**  Bug work-item ids to associate with this result. */
	bug_ids: number[] | null,
};

export type Project = {
	id: string,
	name: string,
};

export type ResultDetail = {
	outcome: string,
	comment: string,
};

export type RunAttachment = {
	file_name: string,
	b64: string,
};

export type RunAttachmentOut = {
	file_name: string,
	b64: string,
};

export type RunCreated = {
	run_id: number,
	web_url: string,
};

export type RunOutcome = {
	outcome: string,
	completed_date: string,
	run_id: number,
};

export type ScreenShot = {
	name: string,
	/**  PNG, base64 (no data: prefix) - the shape add_result_attachment wants. */
	b64_png: string,
};

export type StateInfo = {
	name: string,
	color: string,
	category: string,
};

export type Step = {
	action: string,
	expected: string,
};

export type SubmitItemResult = {
	index: number,
	title: string,
	/**  "created" | "updated" | "failed" */
	action: string,
	id: number | null,
	error: string | null,
};

/**  Emitted once per queue item while submit_queue runs. */
export type SubmitProgress = {
	index: number,
	total: number,
	title: string,
	/**  "created" | "updated" | "failed" */
	action: string,
};

export type SuiteRef = {
	id: number,
	name: string,
	suite_type: string,
	requirement_id: number | null,
	/**
	 *  Parent suite id so the browser can render the real folder tree
	 *  (None = direct child of the plan's stripped root).
	 */
	parent_id: number | null,
};

/**
 *  Emitted while test plans are being scanned for suites, so Run Tests and
 *  the Suites browser can show "Scanning plans X of Y" instead of a bare
 *  skeleton.
 */
export type SuiteScanProgress = {
	done: number,
	total: number,
};

export type TeamRef = {
	id: string,
	name: string,
};

export type TestCase = {
	title: string,
	steps: Step[],
	/**  Semicolon-separated. */
	tags: string,
	/**  "Not Automated" or "Planned". */
	automation_status: string,
	module_value: string,
	preconditions: string,
	/**  When set, update this existing work item instead of creating a new one. */
	update_id: number | null,
};

/**
 *  A fully-loaded Test Case for the editor: steps parsed from the XML blob,
 *  preconditions flattened to plain text. `id` doubles as update_id when the
 *  editor saves.
 */
export type TestCaseFull = {
	id: number,
	title: string,
	tags: string,
	automation_status: string,
	steps: Step[],
	/**
	 *  Real ADO step ids (document order, aligned with `steps`) - the runner
	 *  needs them to build iterationDetails.
	 */
	step_ids: string[],
	module_value: string,
	preconditions: string,
};

export type TestCaseSummary = {
	id: number,
	title: string,
	tags: string,
	automation_status: string,
};

export type TestPlan = {
	id: number,
	name: string,
	area_path: string,
	root_suite_id: number | null,
};

export type TestPoint = {
	point_id: number,
	test_case_id: number | null,
	test_case_name: string,
	config_name: string,
	tester: string,
	last_outcome: string,
	last_run_id: number | null,
	last_result_id: number | null,
};

export type WorkComment = {
	id: number,
	text: string,
	created_by: string,
	created_date: string,
	avatar_url: string,
};

export type WorkItemDetail = {
	id: number,
	title: string,
	work_item_type: string,
	state: string,
	assigned_to: string,
	assigned_to_unique: string,
	activity: string,
	tags: string,
	area_path: string,
	iteration_path: string,
	remaining_work: number | null,
	completed_work: number | null,
	original_estimate: number | null,
	start_date: string,
	finish_date: string,
	/**
	 *  Description (or ReproSteps for Bugs) flattened to plain text for the
	 *  editor; saving wraps it back into a div like v1's preconditions.
	 */
	description_text: string,
	/**
	 *  The same field's RAW HTML, so the editor can convert it to markdown
	 *  and preserve the formatting ADO stored (bold, lists, links...).
	 */
	description_html: string,
	/**
	 *  Which field the description came from (System.Description or
	 *  Microsoft.VSTS.TCM.ReproSteps) so the save writes the right one.
	 */
	description_field: string,
	/**
	 *  The process's extra form pages (Bug: RCA, Preventive Measures...)
	 *  with every visible field on them, shown as editable tabs.
	 */
	extra_pages: ExtraPage[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

